# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/AVTEC_FINAL/pwm_avtec/pwm_avtec.cache/wt [current_project]
set_property parent.project_path D:/AVTEC_FINAL/pwm_avtec/pwm_avtec.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib D:/AVTEC_FINAL/pwm_avtec/pwm_avtec.srcs/sources_1/new/pwm_v.vhd
synth_design -top pwm_v -part xc7a35tcpg236-1
write_checkpoint -noxdef pwm_v.dcp
catch { report_utilization -file pwm_v_utilization_synth.rpt -pb pwm_v_utilization_synth.pb }
